spring:
  datasource:
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/northwind

springdoc:
  swagger-ui:
    path: /swagger-ui